### ISSUE TITLE
Sending Messages

### ISSUE THREAD

**Issue by tradename** [joaosouz4dev/venom-bot-express#1]
Hi Joasouz4dev. Thanks for sharing, aparently when trying to send a message or do anything after authentication its saying Esta sessão não está verificada on everyt request.

**Comment by tradename** [comment]
could there be an issue with function **verify_session**

**Comment by joaosouz4dev** [comment]
I will check and fix, are you using this project?

**Comment by tradename** [comment]
alright , yes im using this project

**Comment by joaosouz4dev** [comment]
that's cool, I'll fix it for you soon.

**Comment by tradename** [comment]
thank you very much..

**Comment by joaosouz4dev** [comment]
@tradename try using again

**Comment by tradename** [comment]
okay, let me do

**Comment by tradename** [comment]
works perfect. thank you
